### ISSUE TITLE
Pathfile as URL

### ISSUE THREAD

**Issue by katagen** [lmotta/catalog-on-the-fly#2]
Hi,
I have a lot of raster and I want to make a catalog on the fly. My problem is that I don't want to dowload all the files. In QGIS, it is possible to load a raster through a URL.
But in the plugin "catalog on the fly", I wasn't able to put this URL in the "pathfile" attribute...

Is there a solution for that? So when I run the plugin it only load the selected rasters!
Thx

**Comment by lmotta** [comment]
Hi,

1) URL:
At the moment, this plugin identify the URL, where, have the XML in the end. The XML is a GDAL WMS driver.
Can you send me a example of your URL.

2) Selected rasters:
Yes, in the table of plugin, only the selected layers are run.
If layer have selected features, only theses are add in project, otherwise, all features add.
Only features in the map view are add.

**Comment by katagen** [comment]
Hi,
Here is an exemple: https://data.geo.admin.ch/ch.swisstopo.landeskarte-farbe-10/swiss-map-raster10_2020_1308-3/swiss-map-raster10_2020_1308-3_krel_0.5_2056.tif

**Comment by lmotta** [comment]
Hi,
Update plugin(2.8).
Thanks Katagen
